In [3]:
# Amboy Numpy Activity

import numpy as np

a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12]])

print (a + b)

[[ 8 10 12]
 [14 16 18]]


In [5]:
a = np.array([[1,2,3], [10,11,15]])
b = 2 * a

print(b)

[[ 2  4  6]
 [20 22 30]]


In [6]:
z = np.array([[20,30,40], [2,3,4]])
r = z * 5

print(r)

[[100 150 200]
 [ 10  15  20]]


In [7]:
g = np.array([[2,4,6,8,10], [11,12,13,14,15]])
j = np.array([[3,6,9,12,15], [22,21,31,41,15]])
c = g + j

print(c)

[[ 5 10 15 20 25]
 [33 33 44 55 30]]
