NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

In [37]:
import numpy as np
import pandas as pd

my_list = [1,2,3]
my_list

[1, 2, 3]

In [38]:
np.array(my_list)

array([1, 2, 3])

In [39]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [40]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
data = pd.DataFrame(np.array(my_matrix),
                    columns=['sunny','rainy','cloudy'],
                    index=['Jan', 'Feb', 'Mar'])

data

sunny  rainy  cloudy
Jan      1      2       3
Feb      4      5       6
Mar      7      8       9

arange

In [42]:
#start 0 to not greater than 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#start 0 to not greater than 11 but 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

zeros and ones

In [44]:
np.zeros(3)

array([0., 0., 0.])

In [45]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

linspace

In [47]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [48]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye - Creates an identity matrix

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random - Numpy also has lots of ways to create random number arrays:

rand - Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].

In [50]:
np.random.rand(2)

array([0.32525378, 0.88929841])

In [51]:
np.random.rand(5,5)

array([[0.20597722, 0.88890502, 0.28959228, 0.94896965, 0.115875  ],
       [0.64367154, 0.32611377, 0.49965891, 0.62481942, 0.07924839],
       [0.10198233, 0.00334966, 0.03593744, 0.86973824, 0.78678213],
       [0.77664552, 0.39513394, 0.28024266, 0.0945643 , 0.73140099],
       [0.2376112 , 0.82637   , 0.63229436, 0.00647016, 0.44165702]])

randn - Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [52]:
np.random.randn(2)

array([0.90152164, 1.95822845])

In [53]:
np.random.randn(5,5)

array([[-0.2280839 ,  0.70609045, -0.04884116, -1.58801156,  1.68054757],
       [-0.13147489,  1.71436282,  1.32449797, -0.65289062,  0.70259082],
       [ 0.02993482,  1.11443556, -2.68450542, -0.03111975, -0.37604808],
       [ 0.56642403, -0.42637472,  0.05459053, -1.1296572 , -0.33223405],
       [ 1.06914703,  0.05135171,  1.00315415, -0.24574721, -0.06282444]])

randint - Return random integers from low (inclusive) to high (exclusive).

In [54]:
np.random.randint(1,100)

53

In [55]:
np.random.randint(1,100,10)

array([80, 10, 63, 59, 90, 15, 68, 16, 41, 73])

Array Attributes and Methods

In [56]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
ranarr

array([28, 30, 47, 48, 12,  6, 16, 14, 17, 44])

Reshape - Returns an array containing the same data with a new shape.

In [59]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arrdata = pd.DataFrame(arr.reshape(5,5))
arrdata

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

Shape and Size

In [61]:
arrdata.size

25

In [62]:
arrdata.shape

(5, 5)

max,min,argmax,argmin

In [63]:
ranarr.max()

48

In [64]:
ranarr.min()

6

In [65]:
ranarr.argmax()

3

In [66]:

ranarr.argmin()

5

Bracket Indexing and Selection

In [67]:
arr[8]

8

In [68]:
arr[1:5]

array([1, 2, 3, 4])

---------------------------------------------------------------------------------------------------------------------

Activity in Data Sciences

In [69]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12]])

print (a + b)

[[ 8 10 12]
 [14 16 18]]


In [70]:
a = np.array([[1,2,3], [10,11,15]])
b = 2 * a

print(b)

[[ 2  4  6]
 [20 22 30]]


In [71]:
z = np.array([[20,30,40], [2,3,4]])
r = z * 5

print(r)

[[100 150 200]
 [ 10  15  20]]


In [72]:
g = np.array([[2,4,6,8,10], [11,12,13,14,15]])
j = np.array([[3,6,9,12,15], [22,21,31,41,15]])
c = g + j

print(c)

[[ 5 10 15 20 25]
 [33 33 44 55 30]]
